hint: 'Is the service a public, private, community or hybrid cloud service?'
depends:
  -
    "on": lot
    being:
      - SaaS
      - saas
      - PaaS
      - paas
      - IaaS
      - iaas
assuranceApproach: 3answers-type1
type: radios
options:
    -
        label: 'Public cloud'
    -
        label: 'Community cloud'
    -
        label: 'Private cloud'
    -
        label: 'Hybrid cloud'
validations:
  -
    name: answer_required
    message: 'You need to answer this question.'
  -
    name: assurance_required
    message: 'You need to confirm how you can back up your response.'
question: 'Cloud deployment model'
