hint: 'Do you track the status, location and configuration of service components throughout their lifetime?'
depends:
  -
    "on": lot
    being:
      - PaaS
      - paas
      - IaaS
      - iaas
assuranceApproach: 2answers-type1
type: boolean
validations:
  -
    name: answer_required
    message: 'You need to answer this question.'
  -
    name: assurance_required
    message: 'You need to confirm how you can back up your response.'
question: 'Configuration and change management tracking'
