hint: 'Do you provide guidance on service configuration options and the relative impacts on security?'
depends:
  -
    "on": lot
    being:
      - PaaS
      - paas
      - IaaS
      - iaas
assuranceApproach: 3answers-type2
type: boolean
validations:
  -
    name: answer_required
    message: 'You need to answer this question.'
  -
    name: assurance_required
    message: 'You need to confirm how you can back up your response.'
question: 'Service configuration guidance'
